/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      screens: {
        /* Addendum breakpoints: 3 cols at 1200+, 4 cols at 1440+ */
        desktop: '1200px',
        'desktop-lg': '1440px',
      },
      colors: {
        /* Design-token mapped scalars — restyle everything from :root vars */
        accent: 'rgb(var(--immo-accent) / <alpha-value>)',
        'accent-strong': 'rgb(var(--immo-accent-strong) / <alpha-value>)',
        ink: 'rgb(var(--immo-ink) / <alpha-value>)',
        field: 'rgb(var(--immo-field) / <alpha-value>)',
        line: 'rgb(var(--immo-border) / <alpha-value>)',
        subtle: 'rgb(var(--immo-subtle) / <alpha-value>)',
        primary: 'rgb(var(--immo-text) / <alpha-value>)',
        secondary: 'rgb(var(--immo-text-2) / <alpha-value>)',
        placeholder: 'rgb(var(--immo-text-placeholder) / <alpha-value>)',
        bg: 'rgb(var(--immo-bg) / <alpha-value>)',
        surface: 'rgb(var(--immo-surface) / <alpha-value>)',
        tileaccent: 'rgb(var(--immo-tile-accent) / <alpha-value>)',
        tilenavy: 'rgb(var(--immo-tile-navy) / <alpha-value>)',
        verified: 'rgb(var(--immo-verified) / <alpha-value>)',
        partial: 'rgb(var(--immo-partial) / <alpha-value>)',
        notVerified: 'rgb(var(--immo-danger) / <alpha-value>)',
        brand: {
          50: 'rgb(238 244 255 / <alpha-value>)',
          100: 'rgb(219 231 255 / <alpha-value>)',
          200: 'rgb(184 206 255 / <alpha-value>)',
          300: 'rgb(133 170 255 / <alpha-value>)',
          400: 'rgb(77 134 255 / <alpha-value>)',
          500: 'rgb(30 107 255 / <alpha-value>)',
          600: 'rgb(0 87 255 / <alpha-value>)',
          700: 'rgb(0 67 204 / <alpha-value>)',
          800: 'rgb(0 53 153 / <alpha-value>)',
          900: 'rgb(0 42 125 / <alpha-value>)',
          950: 'rgb(0 26 77 / <alpha-value>)',
        },
        gray: {
          50: 'rgb(var(--immo-subtle) / <alpha-value>)',
          100: 'rgb(var(--immo-field) / <alpha-value>)',
          200: 'rgb(var(--immo-border) / <alpha-value>)',
          300: 'rgb(var(--immo-gray-300) / <alpha-value>)',
          400: 'rgb(var(--immo-gray-400) / <alpha-value>)',
          500: 'rgb(var(--immo-text-2) / <alpha-value>)',
          600: 'rgb(var(--immo-gray-600) / <alpha-value>)',
          700: 'rgb(var(--immo-gray-700) / <alpha-value>)',
          800: 'rgb(var(--immo-gray-800) / <alpha-value>)',
          900: 'rgb(var(--immo-text) / <alpha-value>)',
          950: 'rgb(17 17 17 / <alpha-value>)',
        },
      },
      fontFamily: {
        sans: ['Roboto', 'Inter', '"Helvetica Neue"', 'Helvetica', 'Arial', 'system-ui', 'sans-serif'],
        display: ['"YouTube Sans"', 'Roboto', 'Inter', '"Helvetica Neue"', 'Helvetica', 'Arial', 'sans-serif'],
      },
      fontSize: {
        /* Studio-style scale — 8px multiples, Roboto workhorse. */
        xs: '0.75rem',
        sm: '0.8125rem',
        base: '0.875rem',
        lg: '1rem',
        xl: '1.0625rem',
        '2xl': '1.125rem',
        '3xl': '1.5rem',
        '4xl': '1.75rem',
        '5xl': '2rem',
        '6xl': '2.25rem',
        '7xl': '2.75rem',
        '8xl': '3.25rem',
        '9xl': '4rem',
        /* Tokens — map to the same scale */
        h1: ['var(--fs-h1)', { lineHeight: '1.15' }],
        h2: ['var(--fs-h2)', { lineHeight: '1.3' }],
        h3: ['var(--fs-h3)', { lineHeight: '1.36' }],
        body: ['var(--fs-body)', { lineHeight: '1.5' }],
        meta: 'var(--fs-meta)',
        ui: ['var(--fs-ui)', { lineHeight: '1.4' }],
        search: 'var(--fs-search)',
        bigstat: ['var(--fs-bigstat)', { lineHeight: '1.1' }],
        'card-agent': 'var(--fs-card-agent)',
        'card-stats': 'var(--fs-card-stats)',
        'card-title': 'var(--fs-card-title)',
        'card-loc': 'var(--fs-card-loc)',
        'card-price': 'var(--fs-card-price)',
      },
      borderRadius: {
        xl: '0.625rem',
        '2xl': '0.75rem',
        '3xl': '1rem',
        '4xl': '2rem',
        tile: 'var(--radius-tile)',
        'card-image': 'var(--radius-card-image)',
        pillar: '999px',
      },
      boxShadow: {
        soft: '0 1px 2px rgb(25 25 25 / 0.04), 0 2px 10px rgb(25 25 25 / 0.05)',
        pop: '0 4px 16px rgb(25 25 25 / 0.08), 0 8px 28px rgb(25 25 25 / 0.1)',
      },
    },
  },
  plugins: [],
};